"""empty message

Revision ID: 909198cb648e
Revises: 16fdd5e95199
Create Date: 2019-04-07 23:03:40.940648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '909198cb648e'
down_revision = '16fdd5e95199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.Text(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
